stages:
  export_pg_procedures:
    cmd: python utils/export_pg_procedures.py
    deps:
    - utils/export_pg_procedures.py
    outs:
    - input_extraction/raw_data.sql
    always_changed: true
  app:
    cmd: python app.py
    deps:
    - input_extraction/raw_data.sql
    - app.py
    outs:
    - output/processed_data.sql
    always_changed: true