CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    active NUMBER(1),
    description CLOB,
    created_at TIMESTAMP DEFAULT NOW()
);

SELECT * FROM users WHERE description LIKE '%admin%';
